//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiTest.Models.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        public int PRODUCTID { get; set; }
        public string PRODUCTNAME { get; set; }
        public int SUPPLIERID { get; set; }
        public int CATEGORYID { get; set; }
        public decimal QUANTITYPERUNITY { get; set; }
        public decimal UNITPRICE { get; set; }
        public decimal UNITSINSTOCKS { get; set; }
        public decimal UNITSONORDER { get; set; }
        public int REORDERLEVEL { get; set; }
        public bool DISCONTINUED { get; set; }
    
        public virtual CATEGORy CATEGORy { get; set; }
        public virtual SUPPLIER SUPPLIER { get; set; }
    }
}
