//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiTest.Models.DATA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class NORTHWINDEntities : DbContext
    {
        public NORTHWINDEntities()
            : base("name=NORTHWINDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PRODUCT> PRODUCTS { get; set; }
        public virtual DbSet<CATEGORy> CATEGORIES { get; set; }
        public virtual DbSet<SUPPLIER> SUPPLIERS { get; set; }
    
        public virtual ObjectResult<SpListadoProducto_Result> SpListadoProducto()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SpListadoProducto_Result>("SpListadoProducto");
        }
    }
}
